### ISSUE TITLE
Resolve problem with cassandra tables

### ISSUE THREAD

**Issue by Mequrel** [Adebski/video-recommender#7]
There is a strange issue with CassandraClient and cassandra driver. We create a table with uppercase characters in the name and its lowercased later. Some queries are forced to use the lowercase version, some of them not. We should at least hide the .toLowerCase method invocation from the user of the client.

**Comment by Adebski** [comment]
http://docs.datastax.com/en/cql/3.0/cql/cql_reference/ucase-lcase_r.html. Does this leak somewhere to the user of the CassandraClient class?

**Comment by Mequrel** [comment]
Take a look at https://github.com/Adebski/video-recommender/blob/master/src/main/scala/ztis/model/ModelBuilder.scala#L160

**Comment by Mequrel** [comment]
As far as I remember if you forget about double quotes you may have a problem with table name. We should always use keyspace."$tablename$ form

**Comment by Adebski** [comment]
Ok I will change it to quotes, without quotes Cassandra does toLowerCase so probably that was the case.
