### ISSUE TITLE
Enhance CassandraClient with Spark methods

### ISSUE THREAD

**Issue by Mequrel** [Adebski/video-recommender#8]
I think we should hide all details about the cassandra config, table names in the CassandraClient class or similar. Maybe it should expose ready to use RDD.

**Comment by Adebski** [comment]
As far as I can see everything about tables/keyspaces/contact-points is encapsulated inside CassandraClient class - what do you have in mind exactly?

**Comment by Mequrel** [comment]
Take a look at https://github.com/Adebski/video-recommender/blob/master/src/main/scala/ztis/model/ModelBuilder.scala#L160

**Comment by Adebski** [comment]
OK, forgot about that.
